### ISSUE TITLE
Couldnt install

### ISSUE THREAD

**Issue by Tanmay2k3** [Neonx99/mope.io-bots#1]
instructon not cleer. I punch wall but no bats, welp

**Comment by SergeantShadoww** [comment]
You need to calling FBI they giving you HQ support.

**Comment by neonnd** [comment]
call obama he will help you

**Comment by SSYYMMPPLLEEXX** [comment]
> ligue para obama ele vai te ajudar

Plis help me Neonx, I have to install GitHub Desktop ?
